create table "public"."badges" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "description" text not null,
    "image" text
);


alter table "public"."badges" enable row level security;

create table "public"."player_badges" (
    "awarded_on" timestamp with time zone not null default now(),
    "player_id" uuid not null default gen_random_uuid(),
    "badge_id" bigint not null
);


alter table "public"."player_badges" enable row level security;

CREATE UNIQUE INDEX badges_pkey ON public.badges USING btree (id);

CREATE UNIQUE INDEX player_badges_pkey ON public.player_badges USING btree (player_id, badge_id);

alter table "public"."badges" add constraint "badges_pkey" PRIMARY KEY using index "badges_pkey";

alter table "public"."player_badges" add constraint "player_badges_pkey" PRIMARY KEY using index "player_badges_pkey";

alter table "public"."player_badges" add constraint "public_player_badges_badge_id_fkey" FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE not valid;

alter table "public"."player_badges" validate constraint "public_player_badges_badge_id_fkey";

alter table "public"."player_badges" add constraint "public_player_badges_player_id_fkey" FOREIGN KEY (player_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."player_badges" validate constraint "public_player_badges_player_id_fkey";

grant delete on table "public"."badges" to "anon";

grant insert on table "public"."badges" to "anon";

grant references on table "public"."badges" to "anon";

grant select on table "public"."badges" to "anon";

grant trigger on table "public"."badges" to "anon";

grant truncate on table "public"."badges" to "anon";

grant update on table "public"."badges" to "anon";

grant delete on table "public"."badges" to "authenticated";

grant insert on table "public"."badges" to "authenticated";

grant references on table "public"."badges" to "authenticated";

grant select on table "public"."badges" to "authenticated";

grant trigger on table "public"."badges" to "authenticated";

grant truncate on table "public"."badges" to "authenticated";

grant update on table "public"."badges" to "authenticated";

grant delete on table "public"."badges" to "service_role";

grant insert on table "public"."badges" to "service_role";

grant references on table "public"."badges" to "service_role";

grant select on table "public"."badges" to "service_role";

grant trigger on table "public"."badges" to "service_role";

grant truncate on table "public"."badges" to "service_role";

grant update on table "public"."badges" to "service_role";

grant delete on table "public"."player_badges" to "anon";

grant insert on table "public"."player_badges" to "anon";

grant references on table "public"."player_badges" to "anon";

grant select on table "public"."player_badges" to "anon";

grant trigger on table "public"."player_badges" to "anon";

grant truncate on table "public"."player_badges" to "anon";

grant update on table "public"."player_badges" to "anon";

grant delete on table "public"."player_badges" to "authenticated";

grant insert on table "public"."player_badges" to "authenticated";

grant references on table "public"."player_badges" to "authenticated";

grant select on table "public"."player_badges" to "authenticated";

grant trigger on table "public"."player_badges" to "authenticated";

grant truncate on table "public"."player_badges" to "authenticated";

grant update on table "public"."player_badges" to "authenticated";

grant delete on table "public"."player_badges" to "service_role";

grant insert on table "public"."player_badges" to "service_role";

grant references on table "public"."player_badges" to "service_role";

grant select on table "public"."player_badges" to "service_role";

grant trigger on table "public"."player_badges" to "service_role";

grant truncate on table "public"."player_badges" to "service_role";

grant update on table "public"."player_badges" to "service_role";


