export const ABILITIES = {
	CUTPURSE: 1,
	CRIMSON_REAP: 2,
	INFERNAL_RAGE: 3,
	DIVINE_AEGIS: 4,
	PROTECTORS_OATH: 5
} as const;

export const DIVINE_AEGIS_PERCENTAGE = 0.75;
export const PROTECTORS_OATH_PERCENTAGE = 0.25;
