name: CI
on:
  push:
    branches:
      - '**'
env:
  CI: true
  PUBLIC_SUPABASE_URL: https://public-supabase-url.com
  PUBLIC_SUPABASE_ANON_KEY: some-public-supabase-anon-key
  SUPABASE_SERVICE_KEY: some-public-supabase-anon-key
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  OPENAI_API_KEY: some-openai-api-key
  PUBLIC_SENTRY_DNS: https://e3619164ee187231b7ee10d1eabfed75@o4506763794972672.ingest.sentry.io/4506763796938752
  PUBLIC_ENV: ci
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate TypeScript configuration
        run: pnpm svelte-kit sync

      - name: Run linting
        run: pnpm run lint

      - name: Type check
        run: pnpm check

      - name: Build
        run: pnpm run build
