name: CI
on:
  push:
    branches:
      - '**'
env:
  CI: true
  PUBLIC_SUPABASE_URL: https://public-supabase-url.com
  PUBLIC_SUPABASE_ANON_KEY: some-public-supabase-anon-key
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm run lint && pnpm run build
